apiVersion: apps/v1
kind: Deployment
metadata:
  name: baz
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar-nginx
  template:
    metadata:
      labels:
        app: bar-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80